{% set name = "backports.lzma" %}
{% set version = "0.0.8" %}
{% set sha256 = "200584ad5079d8ca6b1bfe14890c7be58666ab0128d8ca26cfb2669b476085f3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-Add-another-fallback-for-test.support-import.patch
    - 0002-Fix-name-of-extension.patch
    - 0003-Compute-name-of-lzma-library.patch
    - 0004-Add-compiler-flag-to-realign-stack-for-32bit-gcc.patch

build:
  number: 2
  script:
    - python setup.py build_ext --include-dirs "%LIBRARY_PREFIX%\\mingw-w64\\include" --library-dirs "%LIBRARY_PREFIX%\\mingw-w64\\lib"  # [win and py27]
    - python setup.py install

requirements:
  host:
    - python
    - backports
    - xz                   # [unix or py3k]
    - m2w64-xz             # [win and py2k]
    - m2w64-toolchain      # [win and py2k]
    - libpython            # [win and py2k]

  build:
    - {{ compiler('c') }}  # [unix]

  run:
    - python
    - backports
    # Run exports will take care of xz
    - {{ pin_compatible('m2w64-xz') }}  # [win and py2k]
    - {{ n }}gcc-libs                   # [win and py2k]
    - future                            # [py2k]

test:
  source_files:
    - test
  imports:
    - backports
    - backports.lzma
  commands:
    - python -m unittest discover -s test

about:
  home: https://github.com/peterjc/backports.lzma
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Backport of Python 3.3's 'lzma' module for XZ/LZMA compressed files.

extra:
  recipe-maintainers:
    - alimanfoo
    - groutr
    - jakirkham
    - nehaljwani
